cd C:\Projects\oz_coding\ozcodingschool_be_02_homework\9___webCrawlingProject\flaskapp
set FLASK_APP=index
set FLASK_DEBUG=true
C:\Projects\oz_coding\ozcodingschool_be_02_homework\9___webCrawlingProject\venv\Scripts\activate