# Generated by Django 5.0.3 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_busines_user_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
