-- use mysql;
-- create user 'username'@'localhost' identified by 'oz-password';
-- set password for 'username'@'%' = '신규비밀번호';
-- select * from user;
-- grant all privileges on *.* to 'username'@'localhost';
-- show grants for 'username'@'localhost';
-- show grants;
-- drop user 'username'@'localhost';
