"""empty message

Revision ID: 386f88a0faae
Revises: 
Create Date: 2024-02-08 23:25:49.144664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '386f88a0faae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyobo_price',
    sa.Column('priceId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('inputDate', sa.Date(), nullable=True),
    sa.Column('kyoboPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kyoboSalePrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kyoboPoint', sa.Integer(), nullable=True),
    sa.Column('kyobourl', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('priceId')
    )
    op.create_table('kyobo_ranking',
    sa.Column('rankingId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('inputDate', sa.Date(), nullable=True),
    sa.Column('kyoboRank', sa.Integer(), nullable=True),
    sa.Column('kyoboRating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('kyoboReview', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('rankingId')
    )
    op.create_table('yes24_price',
    sa.Column('priceId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('inputDate', sa.Date(), nullable=True),
    sa.Column('yes24Price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yes24SalePrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yes24Point', sa.Integer(), nullable=True),
    sa.Column('yes24url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('priceId')
    )
    op.create_table('yes24_ranking',
    sa.Column('rankingId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('inputDate', sa.Date(), nullable=True),
    sa.Column('yes24Rank', sa.Integer(), nullable=True),
    sa.Column('yes24Rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('yes24Review', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('rankingId')
    )
    op.drop_table('kyoboranking')
    op.drop_table('kyoboprice')
    op.drop_table('yes24ranking')
    op.drop_table('yes24price')
    with op.batch_alter_table('average', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
        batch_op.drop_constraint('average_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['isbn'], ['isbn'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('coverUrl',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('coverUrl',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('average', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('average_ibfk_1', 'books', ['isbn'], ['isbn'], ondelete='CASCADE')
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)

    op.create_table('yes24price',
    sa.Column('priceId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('inputDate', sa.DATE(), nullable=True),
    sa.Column('yes24Price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('yes24SalePrice', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('yes24Point', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yes24url', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], name='yes24price_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('priceId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('yes24ranking',
    sa.Column('rankingId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('inputDate', sa.DATE(), nullable=True),
    sa.Column('yes24Rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yes24Rating', mysql.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('yes24Review', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], name='yes24ranking_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rankingId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('kyoboprice',
    sa.Column('priceId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('inputDate', sa.DATE(), nullable=True),
    sa.Column('kyoboPrice', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('kyoboSalePrice', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('kyoboPoint', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kyobourl', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], name='kyoboprice_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('priceId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('kyoboranking',
    sa.Column('rankingId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('inputDate', sa.DATE(), nullable=True),
    sa.Column('kyoboRank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kyoboRating', mysql.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('kyoboReview', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], name='kyoboranking_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rankingId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('yes24_ranking')
    op.drop_table('yes24_price')
    op.drop_table('kyobo_ranking')
    op.drop_table('kyobo_price')
    # ### end Alembic commands ###
