"""empty message

Revision ID: b7c8f9958e6a
Revises: 386f88a0faae
Create Date: 2024-02-10 18:09:32.695731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7c8f9958e6a'
down_revision = '386f88a0faae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('average', schema=None) as batch_op:
        batch_op.alter_column('averageWeekRanking',
               existing_type=mysql.DECIMAL(precision=3, scale=1),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('average', schema=None) as batch_op:
        batch_op.alter_column('averageWeekRanking',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=3, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###
