# Generated by Django 5.0.3 on 2024-03-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_busines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_busines',
            new_name='is_business',
        ),
    ]
