# Generated by Django 5.0.3 on 2024-03-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_busines',
            field=models.BooleanField(default=False),
        ),
    ]
